### ISSUE TITLE
File uploads only try to upload test.pdf

### ISSUE THREAD

**Issue by doyougnu** [power10dan/tldrResearchPaper#3]
I boot tldr, click Upload, window pops up, I add a pdf:

Expected Behavior:
I expect that the server output will show the file being uploaded

Actual Behavior:
The server shows that test.pdf is not found **regardless of the pdf file I choose to upload**:

Here is the output:

```
Performing system checks...

System check identified no issues (0 silenced).
October 13, 2017 - 16:58:05
Django version 1.11.5, using settings 'uploads.settings.settings_dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /api/uploadFile/test.pdf
Traceback (most recent call last):
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/doyougnu/.virtualenvs/tldr/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/doyougnu/School_Files/Hoops_17-18/Fall/SE/tldrResearchPaper/uploads/views/views.py", line 30, in post
    with open(path, 'w') as fileopened:
IOError: [Errno 2] No such file or directory: u'/home/doyougnu/School_Files/Hoops_17-18/Fall/SE/tldrResearchPaper/uploads/media/documents/test.pdf'
[13/Oct/2017 17:00:21] "POST /api/uploadFile/test.pdf HTTP/1.1" 500 18249
```

I believe the issue is in `UploadFile.js` specifically here:
```js
handleClick = (fileObj) =>{
	//console.log(fileObj.fileList[0])
	var djangoURL = "http://127.0.0.1:8000/api/uploadFile/".concat("test.pdf");
	var blob = fileObj.base64;
	this.uploadFiles(djangoURL, blob);
}
```

**Comment by mihaidan** [comment]
I did a fresh install and tried uploading a file. It went through fine, except the output in the back end is weird. I attached the 'test.pdf' file that was created.
[test.pdf](https://github.com/power10dan/tldrResearchPaper/files/1383489/test.pdf)

**Comment by doyougnu** [comment]
This was due to a bug in UploadFile.js and the backend views.py. See 617463cfe133896979af9a2bb65507b99f0f8192 and 124f09aff69dd3e26a88ea5c0b0502f6758cbbef. Issue is closed.
